name: Continuous Delivery Presentation
run-name: ${{ github.actor }} runs compile sources 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 12
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        # will push to docker repository
      - name: Build and push to public repository
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/democalc_public:latest

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Update Notifier
          SLACK_ICON_EMOJI: ':bell:'
          SLACK_MESSAGE: We have new changes - ${{ github.event.head_commit.message }}. In order to download use 'docker run --name democalc_container1 -it --entrypoint /bin/sh gerwald/democalc_public:latest
          SLACK_COLOR: '#efefef'



